# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

# not using batteries for now, so no battery status needed
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n

# disable for right side. only works on left for now
CONFIG_ZMK_WPM=n
CONFIG_ZMK_WIDGET_WPM_STATUS=n
